export const languages = {
  ru: {
    search: "Я хочу найти...",
    profile: "Профиль",
    basket: "Корзина",
    russian: "русский",
    kazakh: "казахский",
    more: "Подробнее",
    notfound: "Ничего не найдено",
    incart: "В корзину",
    addedtocart: "Товар успешно добавлен в корзину",
    alreadyInCart: "Этот товар уже в корзине",
    all: "Все",
    devicetype: {
      smartphone: "Смартфон",
      tablet: "Планшет",
      tv: "Телевизор",
      keyboard: "Клавиатура",
      mouse: "Мышь",
      monitor: "Монитор",
      printer: "Принтер",
      laptop: "Ноутбук",
      desktop: "Компьютер",
    },
  },
  kz: {
    search: "Мен тапқым келеді...",
    profile: "Профиль",
    basket: "Себет",
    russian: "орыс",
    kazakh: "қазақ",
    more: "Толығырақ",
    notfound: "Ештеңе табылмады",
    incart: "Себетке қосу",
    addedtocart: "Тауар сәтті түрде себетке қосылды",
    alreadyInCart: "Бұл зат себетте",
    all: "Барлығы",
    devicetype: {
      smartphone: "Смартфон",
      tablet: "Планшет",
      tv: "Теледидар",
      keyboard: "Пернетақта",
      mouse: "Тінтуір",
      monitor: "Монитор",
      printer: "Принтер",
      laptop: "Ноутбук",
      desktop: "Компьютер",
    },
  },
};
